version: '2'
services:
  db:
    image: mysql
    container_name: Yii2-mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "testuser1"
      MYSQL_PASSWORD: "123456"
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: always
  php:
    image: php:7-fpm-alpine
    container_name: Yii2_php-fpm
    restart: always
    volumes:
      - ./www/:/var/www/html
    expose:
      - "9000"
  nginx:
    image: nginx:alpine
    container_name: Yii2_nginx
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    volumes_from:
      - php
    ports:
      - 80:80
